import fs from "fs";
import path from "path";
import PDFDocument from "pdfkit";
import type { Response } from "express";

function text(doc: PDFKit.PDFDocument, label: string, value: unknown, x?: number, y?: number) {
  const v = value === null || value === undefined || value === "" ? "—" : String(value);
  if (x !== undefined && y !== undefined) {
    doc.font("Helvetica-Bold").fontSize(8).fillColor("#64748b").text(label.toUpperCase(), x, y);
    doc.font("Helvetica").fontSize(11).fillColor("#0f172a").text(v, x, y + 12, { width: 230 });
  } else {
    doc.font("Helvetica-Bold").fontSize(8).fillColor("#64748b").text(label.toUpperCase());
    doc.font("Helvetica").fontSize(11).fillColor("#0f172a").text(v);
    doc.moveDown(0.4);
  }
}

function section(doc: PDFKit.PDFDocument, title: string) {
  if (doc.y > doc.page.height - 140) doc.addPage();
  doc.moveDown(0.6);
  doc.font("Helvetica-Bold").fontSize(13).fillColor("#123B5D").text(title);
  doc.moveTo(50, doc.y + 4).lineTo(doc.page.width - 50, doc.y + 4).strokeColor("#C7F36B").lineWidth(2).stroke();
  doc.moveDown(0.8);
}

export async function generateReportPdf(report: any, results: any[], res: Response) {
  const doc = new PDFDocument({ margin: 50, size: "A4", bufferPages: true });
  const filename = `Report-${report.applicationNo || "NAWI"}.pdf`;
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename=${filename}`);
  doc.pipe(res);

  let pageNumber = 0;
  const stampFooter = () => {
    const range = doc.bufferedPageRange();
    for (let i = 0; i < range.count; i++) {
      doc.switchToPage(range.start + i);
      const bottom = doc.page.height - 36;
      doc.fontSize(8).fillColor("#64748b").text(
        `MaapSetu NAWI Test Report  ·  ${report.applicationNo}  ·  Page ${i + 1} of ${range.count}  ·  Prototype / synthetic demonstration`,
        50,
        bottom,
        { width: doc.page.width - 100, align: "center" }
      );
    }
  };

  const logoCandidates = [
    path.join(process.cwd(), "public", "assets", "logo.png"),
    path.join(process.cwd(), "public", "assets", "aistudio", "logo.png"),
  ];
  const logoPath = logoCandidates.find((p) => fs.existsSync(p));
  if (logoPath) {
    try {
      doc.image(logoPath, 50, 40, { fit: [56, 56] });
    } catch {
      /* ignore */
    }
  }

  doc.font("Helvetica-Bold").fontSize(18).fillColor("#101214").text("NAWI TEST REPORT", logoPath ? 118 : 50, 48);
  doc.font("Helvetica").fontSize(10).fillColor("#123B5D").text("OIML Recommendation R-76  ·  Non-Automatic Weighing Instruments", logoPath ? 118 : 50, 72);
  doc.fontSize(8).fillColor("#64748b").text("Generated by MaapSetu  ·  Smart India Hackathon prototype", logoPath ? 118 : 50, 88);

  doc.rect(50, 110, doc.page.width - 100, 28).fill("#123B5D");
  doc.fillColor("#C7F36B").font("Helvetica-Bold").fontSize(11).text(
    `OVERALL VERDICT: ${report.overallVerdict || "PENDING"}     STATUS: ${report.status}`,
    60,
    118
  );

  const instrument = report.instrumentId || {};
  const lab = report.laboratoryDetails || {};
  const env = report.environmentalConditions || report.testConditions || {};

  section(doc, "Report identification");
  const y0 = doc.y;
  text(doc, "Report number", report.applicationNo, 50, y0);
  text(doc, "Test date", new Date(report.date || Date.now()).toLocaleDateString("en-IN"), 300, y0);
  text(doc, "Standard reference", report.standardReference, 50, y0 + 40);
  text(doc, "Lead inspector", report.inspector, 300, y0 + 40);
  doc.y = y0 + 90;

  section(doc, "Laboratory details");
  text(doc, "Laboratory", lab.name);
  text(doc, "Address / notes", lab.address);
  text(doc, "Accreditation note", lab.accreditation);

  section(doc, "Instrument details");
  const iy = doc.y;
  text(doc, "Instrument ID", instrument.instrumentId, 50, iy);
  text(doc, "Type", instrument.instrumentType, 300, iy);
  text(doc, "Manufacturer", instrument.manufacturer, 50, iy + 40);
  text(doc, "Model", instrument.model, 300, iy + 40);
  text(doc, "Serial number", instrument.serialNumber, 50, iy + 80);
  text(doc, "Accuracy class", instrument.accuracyClass ? `Class ${instrument.accuracyClass}` : "—", 300, iy + 80);
  text(doc, "Max capacity", instrument.maxCapacity != null ? `${instrument.maxCapacity} kg` : "—", 50, iy + 120);
  text(doc, "Min capacity", instrument.minCapacity != null ? `${instrument.minCapacity} g` : "—", 300, iy + 120);
  text(doc, "Verification scale interval e", instrument.eValue != null ? `${instrument.eValue} g` : "—", 50, iy + 160);
  text(doc, "Actual scale interval d", instrument.dValue != null ? `${instrument.dValue} g` : "—", 300, iy + 160);
  doc.y = iy + 210;

  section(doc, "Environmental conditions");
  const ey = doc.y;
  text(doc, "Temperature", env.temperature || "—", 50, ey);
  text(doc, "Humidity", env.humidity || "—", 220, ey);
  text(doc, "Location", env.location || "—", 390, ey);
  doc.y = ey + 50;

  section(doc, "Test results");
  if (!results.length) {
    doc.font("Helvetica").fontSize(10).fillColor("#64748b").text("No test observations recorded.");
  }

  for (const result of results) {
    if (doc.y > doc.page.height - 160) doc.addPage();
    doc.font("Helvetica-Bold").fontSize(11).fillColor("#101214").text(result.testName || "Test");
    doc.font("Helvetica").fontSize(9).fillColor(result.passed ? "#159A70" : "#E05252").text(
      `Result: ${result.verdict || (result.passed ? "PASS" : "FAIL")}`
    );
    if (result.explanation) {
      doc.font("Helvetica").fontSize(8).fillColor("#475569").text(String(result.explanation), { width: doc.page.width - 100 });
    }
    const data = result.data;
    doc.moveDown(0.3);
    doc.font("Helvetica").fontSize(8).fillColor("#0f172a");
    if (Array.isArray(data)) {
      for (const row of data.slice(0, 40)) {
        if (doc.y > doc.page.height - 80) doc.addPage();
        const line = summarizeRow(row);
        doc.text(line, { width: doc.page.width - 100 });
      }
    } else if (data && typeof data === "object") {
      doc.text(JSON.stringify(data).slice(0, 1200), { width: doc.page.width - 100 });
    }
    doc.moveDown(0.6);
  }

  section(doc, "Review and authorization");
  const reviewer = report.reviewedBy;
  text(doc, "Reviewed by", reviewer?.name || "—");
  text(doc, "Review notes", report.reviewNotes || "—");
  text(doc, "Review date", report.reviewedAt ? new Date(report.reviewedAt).toLocaleDateString("en-IN") : "—");

  doc.moveDown(1.2);
  const sigY = doc.y;
  doc.font("Helvetica").fontSize(9).fillColor("#101214");
  doc.text("Technician / Inspector signature", 50, sigY);
  doc.moveTo(50, sigY + 40).lineTo(230, sigY + 40).strokeColor("#101214").stroke();
  doc.text(report.inspector || "", 50, sigY + 46);

  doc.text("Reviewer / Approver signature", 320, sigY);
  doc.moveTo(320, sigY + 40).lineTo(500, sigY + 40).strokeColor("#101214").stroke();
  doc.text(reviewer?.name || "", 320, sigY + 46);

  doc.moveDown(4);
  doc.fontSize(8).fillColor("#64748b").text(
    "DISCLAIMER: This document is produced by a hackathon prototype. Synthetic/demo laboratory data may be included. It is not an official Legal Metrology certificate and must not be used as a verified regulatory record.",
    50,
    doc.y,
    { width: doc.page.width - 100 }
  );

  if (report.attachments?.length) {
    section(doc, "Supporting attachments");
    for (const a of report.attachments) {
      doc.font("Helvetica").fontSize(9).fillColor("#0f172a").text(`${a.kind || "file"}: ${a.originalName || a.storedName}`);
    }
  }

  stampFooter();
  doc.end();
  pageNumber;
}

function summarizeRow(row: any): string {
  if (row == null) return "";
  if (typeof row !== "object") return String(row);
  const bits = [
    row.position && `Pos ${row.position}`,
    row.series && row.series,
    row.load_point && row.load_point,
    row.minutes != null && `t=${row.minutes} min`,
    (row.testLoad ?? row.load ?? row.test_load_g) != null && `L=${row.testLoad ?? row.load ?? row.test_load_g} g`,
    (row.indication ?? row.ind ?? row.indication_g) != null && `I=${row.indication ?? row.ind ?? row.indication_g} g`,
    (row.error ?? row.err ?? row.error_g) != null && `E=${row.error ?? row.err ?? row.error_g} g`,
    (row.permissibleError ?? row.mpe ?? row.mpe_g) != null && `MPE ${row.permissibleError ?? row.mpe ?? row.mpe_g}`,
    row.result && String(row.result),
  ].filter(Boolean);
  return bits.join("  ·  ") || JSON.stringify(row).slice(0, 180);
}
